const SITE = "https://thrivetools.co";

export interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  href: string;
  canonical: string;
  badge: string;
  badgeColor: string;
  date: string;
  lastmod: string;
}

export interface StaticRoute {
  path: string;
  changefreq: string;
  priority: number;
  lastmod?: string;
}

export interface EventRoute {
  path: string;
  changefreq: string;
  priority: number;
}

export const SITE_URL = SITE;

export const staticRoutes: StaticRoute[] = [
  { path: "/", changefreq: "weekly", priority: 1.0 },
  { path: "/blog", changefreq: "weekly", priority: 0.9 },
  { path: "/discount-codes", changefreq: "weekly", priority: 0.9 },
  { path: "/about", changefreq: "monthly", priority: 0.7 },
  { path: "/contact", changefreq: "monthly", priority: 0.5 },
  { path: "/breathwork", changefreq: "monthly", priority: 0.7 },
  { path: "/events", changefreq: "weekly", priority: 0.7 },
  { path: "/personalized-guidance", changefreq: "monthly", priority: 0.7 },
  { path: "/somatic-reset", changefreq: "monthly", priority: 0.7 },
  { path: "/retreats-workshops", changefreq: "monthly", priority: 0.7 },
];

export const eventRoutes: EventRoute[] = [
  { path: "/events/ayahuasca-journey", changefreq: "monthly", priority: 0.6 },
  { path: "/events/drum-circle", changefreq: "monthly", priority: 0.6 },
  { path: "/events/indoor-gardening", changefreq: "monthly", priority: 0.6 },
  { path: "/events/thrive-1", changefreq: "monthly", priority: 0.6 },
  { path: "/events/cacao-ceremonies", changefreq: "monthly", priority: 0.6 },
  { path: "/events/food-forest", changefreq: "monthly", priority: 0.6 },
  { path: "/events/psilocybin-forest-walk", changefreq: "monthly", priority: 0.6 },
  { path: "/events/thrive-2", changefreq: "monthly", priority: 0.6 },
  { path: "/retreats-workshops/blossoming-bliss", changefreq: "monthly", priority: 0.6 },
  { path: "/retreats-workshops/spiritual-nutrition", changefreq: "monthly", priority: 0.6 },
  { path: "/retreats-workshops/mescaline-wisdom", changefreq: "monthly", priority: 0.6 },
  { path: "/retreats-workshops/inner-silence", changefreq: "monthly", priority: 0.6 },
];

export const blogPosts: BlogPost[] = [
  {
    id: "longevity-molecules-nmn-resveratrol-spermidine-guide",
    title: "The Consumer Guide to Longevity Molecules: Purity Benchmarks for NMN, Resveratrol, and Spermidine",
    excerpt: "The longevity supplement market is flooded with white-labeled, under-dosed powders. Here are the exact purity benchmarks, active forms, and clinical dose targets for NMN, Trans-Resveratrol, and Spermidine — so you can audit your stack and stop paying premium prices for unstandardized ingredients.",
    href: "/blog/longevity-molecules-nmn-resveratrol-spermidine-guide",
    canonical: "/blog/longevity-molecules-nmn-resveratrol-spermidine-guide",
    badge: "Longevity",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "July 6, 2026",
    lastmod: "2026-07-06",
  },
  {
    id: "spirulina-red-light-therapy-photodynamic-action",
    title: "Should You Take Spirulina Before Red Light Therapy? The Science of Chlorophyll Photodynamic Action",
    excerpt: "Spirulina's chlorophyll absorbs at 660–670nm and phycocyanin at 610–650nm — precisely the wavelengths used in clinical PBM panels. Here is the science behind stacking natural photosensitizers with red light therapy, and the exact pre-session protocol to amplify your mitochondrial response.",
    href: "/blog/spirulina-red-light-therapy-photodynamic-action",
    canonical: "/blog/spirulina-red-light-therapy-photodynamic-action",
    badge: "Red Light Therapy",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "June 28, 2026",
    lastmod: "2026-06-28",
  },
  {
    id: "he-shou-wu-ashwagandha-cycling-guide",
    title: "How to Cycle He Shou Wu and Ashwagandha Without Liver Fatigue: A Clinical Stack Guide",
    excerpt: "Stacking He Shou Wu and Ashwagandha is incredibly potent for the nervous system, endocrine balance, and longevity — but both herbs compete for the same CYP450 liver enzymes. Here is the structured cycling protocol that prevents hepatic slowdown and keeps the stack effective long-term.",
    href: "/blog/he-shou-wu-ashwagandha-cycling-guide",
    canonical: "/blog/he-shou-wu-ashwagandha-cycling-guide",
    badge: "Adaptogen Stack",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "June 16, 2026",
    lastmod: "2026-06-16",
  },
  {
    id: "black-seed-oil-benefits-nigella-sativa-guide",
    title: "Black Seed Oil Benefits: What 2,000 Years of Use and Modern Science Both Agree On",
    excerpt: "Black seed (Nigella sativa) has over 1,000 published studies behind it. The active compound thymoquinone is a master regulator of the NF-κB inflammatory pathway, explaining its documented effects on allergies, immunity, metabolic health, gut function, cardiovascular protection, and skin health. This is the honest breakdown of the science.",
    href: "/blog/black-seed-oil-benefits-nigella-sativa-guide",
    canonical: "/blog/black-seed-oil-benefits-nigella-sativa-guide",
    badge: "Science Deep Dive",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "June 13, 2026",
    lastmod: "2026-06-13",
  },
  {
    id: "morning-routine-nervous-system-2026",
    title: "The Morning Routine That Actually Regulates Your Nervous System (Backed by Science)",
    excerpt: "Most morning routines are productivity cosplay. This one is built on how your nervous system actually works — circadian light, adenosine clearance, cortisol rhythm, ceremonial cacao, adaptogens, and magnesium. The 8-step sequence that sets the biological architecture for your entire day.",
    href: "/blog/morning-routine-nervous-system-2026",
    canonical: "/blog/morning-routine-nervous-system-2026",
    badge: "Nervous System",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "June 12, 2026",
    lastmod: "2026-06-12",
  },
  {
    id: "cortisol-face-hpa-axis-guide-2026",
    title: "Cortisol Face Is a Real Thing — But Not for the Reasons TikTok Says",
    excerpt: "Chronic cortisol dysregulation goes far deeper than a puffy face — it affects your brain, metabolism, sleep, immune system, and muscle mass. Eden Laraki breaks down what the HPA axis actually does and the evidence-based protocol that actually works.",
    href: "/blog/cortisol-face-hpa-axis-guide-2026",
    canonical: "/blog/cortisol-face-hpa-axis-guide-2026",
    badge: "Hormones & Stress",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "June 4, 2026",
    lastmod: "2026-06-04",
  },
  {
    id: "microplastics-brain-protocol-2026",
    title: "Microplastics Are in Your Brain. Here's What You Can Actually Do About It.",
    excerpt: "A 2025 Nature Medicine study found microplastics in human brain tissue — 50% more than 2016 samples. Here's what the research actually says, what the wellness industry is getting wrong, and the evidence-based protocol for reducing exposure and supporting your body's natural clearance.",
    href: "/blog/microplastics-brain-protocol-2026",
    canonical: "/blog/microplastics-brain-protocol-2026",
    badge: "Science Deep Dive",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "May 29, 2026",
    lastmod: "2026-05-29",
  },
  {
    id: "biohacker-supplement-stack-2026",
    title: "The Biohacker's Supplement Stack: What I Actually Take and Why (2026)",
    excerpt: "After 14 years of testing supplements, this is the exact stack I take — layered by foundation, system support, longevity, and advanced tools. The science behind every choice, what I've dropped, and what the research says.",
    href: "/blog/biohacker-supplement-stack-2026",
    canonical: "/blog/biohacker-supplement-stack-2026",
    badge: "Full Stack Guide",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "May 21, 2026",
    lastmod: "2026-05-21",
  },
  {
    id: "miso-myth-biologically-dead-fermented-foods",
    title: "The Miso Myth: Why Your Fermented Foods Are Likely Biologically Dead",
    excerpt: "Most miso is pasteurized and biologically inactive. Learn the science of Bacillus subtilis, why raw chickpea miso is superior, and how to make your own living ferment.",
    href: "/blog/miso-myth-biologically-dead-fermented-foods",
    canonical: "/blog/miso-myth-biologically-dead-fermented-foods",
    badge: "Science Deep Dive",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "May 8, 2026",
    lastmod: "2026-05-08",
  },
  {
    id: "kratom-replacing-alcohol-cannabis-social-pivot-2026",
    title: "The Ultimate Social Pivot: Why Kratom is Replacing Alcohol and Cannabis in 2026",
    excerpt: "The search for a middle ground has led millions toward kratom. Here is the honest breakdown of the science, the real long-term risks, the professional protocol, and where to source it safely.",
    href: "/blog/kratom-replacing-alcohol-cannabis-social-pivot-2026",
    canonical: "/blog/kratom-replacing-alcohol-cannabis-social-pivot-2026",
    badge: "Plant Medicine",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "April 20, 2026",
    lastmod: "2026-04-20",
  },
  {
    id: "waterdrop-k19-h-aquatru-rkin-reverse-osmosis-review",
    title: "Waterdrop vs. AquaTru vs. RKIN: The Truth About Zero Installation Reverse Osmosis",
    excerpt: "The genuine, no BS breakdown of the only three countertop RO systems worth considering. UV sterilization, PFAS removal, instant hot water, and why I finally cleared counter space for the Waterdrop K19.H.",
    href: "/blog/waterdrop-k19-h-aquatru-rkin-reverse-osmosis-review",
    canonical: "/blog/waterdrop-k19-h-aquatru-rkin-reverse-osmosis-review",
    badge: "Product Review",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "September 24, 2025",
    lastmod: "2025-09-24",
  },
  {
    id: "muse-headband-review-eeg-neurofeedback",
    title: "Muse Headband Review: The Science-Backed EEG Device That's Changing How We Meditate",
    excerpt: "After 14 years in the biohacking world, the Muse EEG headband is one of the rare devices that earns its place. Here is what 200+ peer-reviewed studies actually say, and my honest verdict.",
    href: "/blog/muse-headband-review-eeg-neurofeedback",
    canonical: "/blog/muse-headband-review-eeg-neurofeedback",
    badge: "Tech Review",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "March 25, 2026",
    lastmod: "2026-03-25",
  },
  {
    id: "cordyceps-cs4-vs-wild-cordyceps-sinensis",
    title: "Cordyceps CS-4 vs Wild Cordyceps Sinensis: Is the Price Difference Worth It?",
    excerpt: "Wild Cordyceps sinensis can cost $50,000 per kilo. CS-4 costs a fraction of that, and the chemistry research may surprise you. Here is my honest verdict after 10 years of daily use.",
    href: "/blog/cordyceps-cs4-vs-wild-cordyceps-sinensis",
    canonical: "/blog/cordyceps-cs4-vs-wild-cordyceps-sinensis",
    badge: "Tonic Herbs Guide",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "March 18, 2026",
    lastmod: "2026-03-18",
  },
  {
    id: "omega-3-complete-guide-epa-dha-fish-oil-vs-algae",
    title: "Omega-3: Everything You Actually Need to Know",
    excerpt: "EPA, DHA, fish oil vs algae oil, optimal dosing, and why most supplements fail. The complete science including the 2025 bioavailability research, the omega-3 index, and the only brand I recommend.",
    href: "/blog/omega-3-complete-guide-epa-dha-fish-oil-vs-algae",
    canonical: "/blog/omega-3-complete-guide-epa-dha-fish-oil-vs-algae",
    badge: "Supplements Guide",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "March 11, 2026",
    lastmod: "2026-03-11",
  },
  {
    id: "pumpkin-seed-oil-supplement-stack-benefits",
    title: "Why Pumpkin Seed Oil Belongs in Every Serious Supplement Stack",
    excerpt: "Brain-protective tryptophan, therapeutic zinc, prostate-specific phytosterols, and deep Kidney Jing nourishment, all in one daily oil. Here's the complete science and the only brand I recommend.",
    href: "/blog/pumpkin-seed-oil-supplement-stack-benefits",
    canonical: "/blog/pumpkin-seed-oil-supplement-stack-benefits",
    badge: "Product Review",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "March 4, 2026",
    lastmod: "2026-03-04",
  },
  {
    id: "magnesium-deficiency-supplement-guide",
    title: "Magnesium: The Most Important Mineral You're Almost Certainly Deficient In",
    excerpt: "Over 31% of the global population is magnesium deficient, and most people supplementing are still deficient because they're taking the wrong forms. Here's the complete science and the only magnesium supplement I personally recommend.",
    href: "/blog/magnesium-deficiency-supplement-guide",
    canonical: "/blog/magnesium-deficiency-supplement-guide",
    badge: "Supplements Guide",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "February 25, 2026",
    lastmod: "2026-02-25",
  },
  {
    id: "reishi-schisandra-daily-tonic-herbs",
    title: "Reishi and Schisandra: The Only Two Plants Beneficial for Every Single Organ in Your Body",
    excerpt: "In 14 years of researching herbs I have never found a more definitive answer to \"what should I take every day for life?\" than these two plants. The 4000 year old science behind why they sit at the top of the highest tier of medicine.",
    href: "/blog/reishi-schisandra-daily-tonic-herbs",
    canonical: "/blog/reishi-schisandra-daily-tonic-herbs",
    badge: "Tonic Herbs Guide",
    badgeColor: "bg-green-500/15 text-green-300 border-green-500/25",
    date: "February 18, 2026",
    lastmod: "2026-02-18",
  },
  {
    id: "bacillus-subtilis-bacillus-coagulans-probiotic-guide",
    title: "Why Most Probiotics Never Reach Your Gut. The Two Strains That Always Do",
    excerpt: "Most probiotic supplements are dead before they reach your gut. Here's the science behind Bacillus subtilis and Bacillus coagulans, the two spore-forming strains that actually survive, and why they're in the only probiotic I personally recommend.",
    href: "/blog/bacillus-subtilis-bacillus-coagulans-probiotic-guide",
    canonical: "/blog/bacillus-subtilis-bacillus-coagulans-probiotic-guide",
    badge: "Science Deep Dive",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "February 11, 2026",
    lastmod: "2026-02-11",
  },
  {
    id: "energybits-spirulina-chlorella-review",
    title: "Spirulina and Chlorella: Why Low-Heat Processing Is the Difference Between a Superfood and an Expensive Disappointment",
    excerpt: "Most spirulina and chlorella supplements destroy their most valuable nutrients with high-heat drying. Here's what that means for your health, and why ENERGYbits is the only brand I trust for algae.",
    href: "/blog/energybits-spirulina-chlorella-review",
    canonical: "/blog/energybits-spirulina-chlorella-review",
    badge: "Honest Review",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "February 4, 2026",
    lastmod: "2026-02-04",
  },
  {
    id: "im8-vs-ag1",
    title: "IM8 vs AG1 (2026): An Honest, Science-Based Comparison",
    excerpt: "We break down ingredients, dosing transparency, quality certifications, taste, price, and who each product is actually right for. No sponsored bias, just the facts.",
    href: "/product-reviews/im8-vs-ag1",
    canonical: "/product-reviews/im8-vs-ag1",
    badge: "Comparison",
    badgeColor: "bg-amber-500/15 text-amber-300 border-amber-500/25",
    date: "January 28, 2026",
    lastmod: "2026-01-28",
  },
  {
    id: "im8-health-review",
    title: "IM8 Health Review (2026): Is It Worth It? An Honest, Science-Based Deep Dive",
    excerpt: "Breaking down the science behind IM8's formula — does this all-in-one supplement actually deliver on its longevity promises? Here's what the research says.",
    href: "/product-reviews/im8-health-review",
    canonical: "/product-reviews/im8-health-review",
    badge: "In-Depth Review",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "January 21, 2026",
    lastmod: "2026-01-21",
  },
  {
    id: "vielight-neuro-review",
    title: "Vielight Neuro Review 2026: Can Photobiomodulation Reverse Brain Aging?",
    excerpt: "Testing the Vielight Neuro Alpha and Gamma devices — examining the clinical research on transcranial photobiomodulation and my personal 6-month experience.",
    href: "/product-reviews/vielight-neuro-review",
    canonical: "/product-reviews/vielight-neuro-review",
    badge: "Tech Review",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "January 14, 2026",
    lastmod: "2026-01-14",
  },
  {
    id: "ketamine-brain-science-nmda-receptors-neuron-regrowth",
    title: "Ketamine and the Brain: What Science Really Says About NMDA Receptors and Neuron Regrowth",
    excerpt: "Ketamine has been called the greatest breakthrough in depression research in 60 years. Here is what the science actually shows about NMDA receptor blockade, BDNF, synaptogenesis, and the S vs R enantiomer debate.",
    href: "/blog/ketamine-brain-science-nmda-receptors-neuron-regrowth",
    canonical: "/blog/ketamine-brain-science-nmda-receptors-neuron-regrowth",
    badge: "Science Deep Dive",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "December 31, 2025",
    lastmod: "2025-12-31",
  },
  {
    id: "hyperion-herbs",
    title: "Experience True Potency: Why I Recommend Hyperion Herbs for Tonic Herbs",
    excerpt: "Why most supplements fail, what makes Hyperion Herbs different, and my personal experience with their Reishi and Schisandra extracts.",
    href: "/product-reviews/hyperion-herbs",
    canonical: "/product-reviews/hyperion-herbs",
    badge: "Herbal Review",
    badgeColor: "bg-green-500/15 text-green-300 border-green-500/25",
    date: "January 7, 2026",
    lastmod: "2026-01-07",
  },
  {
    id: "joovv-review",
    title: "Is Joovv Worth It? A Deep Dive into the Benefits and Results (2026 Edition)",
    excerpt: "Red light therapy has taken the biohacking world by storm — but is Joovv's premium price tag justified? My unfiltered experience after months of daily use.",
    href: "/product-reviews/joovv-review",
    canonical: "/product-reviews/joovv-review",
    badge: "Tech Review",
    badgeColor: "bg-red-500/15 text-red-300 border-red-500/25",
    date: "December 24, 2025",
    lastmod: "2025-12-24",
  },
  {
    id: "earthrunners-review",
    title: "EarthRunners Review (2026): The Only Sandals I Travel, Hike and Run In",
    excerpt: "My honest take after years of daily use — the grounding technology, minimalist design, durability across hiking and jogging, and why one pair does it all.",
    href: "/blog/earthrunners-review",
    canonical: "/blog/earthrunners-review",
    badge: "Honest Review",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "December 17, 2025",
    lastmod: "2025-12-17",
  },
  {
    id: "tonic-herbs-guide",
    title: "Tonic Herbs: The Ancient System of Deep Nourishment Modern Biohackers Are Rediscovering (2026)",
    excerpt: "The highest class of medicine in Traditional Chinese Medicine, used daily for thousands of years to build vitality and extend longevity. The 7 most important herbs, the quality problem, and how to build your protocol.",
    href: "/blog/tonic-herbs-guide",
    canonical: "/blog/tonic-herbs-guide",
    badge: "Complete Guide",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "December 10, 2025",
    lastmod: "2025-12-10",
  },
  {
    id: "mct-oil-benefits-c8-vs-c10-powder-vs-oil",
    title: "MCT Oil Benefits, C8 vs C10, and Oil vs Powder: The Complete Biohacker's Guide (2026)",
    excerpt: "The real science behind MCT oil's benefits, the difference between C8 and C10, whether oil or powder is right for you, and the two products I recommend.",
    href: "/blog/mct-oil-benefits-c8-vs-c10-powder-vs-oil",
    canonical: "/blog/mct-oil-benefits-c8-vs-c10-powder-vs-oil",
    badge: "Complete Guide",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "December 3, 2025",
    lastmod: "2025-12-03",
  },
  {
    id: "mouth-breathing-mouth-taping",
    title: "Mouth Breathing Is Quietly Ruining Your Health, And Most People Have No Idea They're Doing It",
    excerpt: "Chronic mouth breathing silently destroys sleep quality, cognitive function, and facial structure. Here's the science and why mouth taping with MyoTape from Oxygen Advantage is the simplest fix.",
    href: "/blog/mouth-breathing-mouth-taping",
    canonical: "/blog/mouth-breathing-mouth-taping",
    badge: "Health Guide",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "November 26, 2025",
    lastmod: "2025-11-26",
  },
  {
    id: "creatine-dosage-for-brain",
    title: "Why 5g of Creatine Isn't Enough for Your Brain: The Case for 10g (2026)",
    excerpt: "You've been taking 5g of creatine for your muscles. But new research, backed by Dr. Rhonda Patrick, Andrew Huberman, and Dr. Darren Candow, shows your brain needs more. Here's why.",
    href: "/blog/creatine-dosage-for-brain",
    canonical: "/blog/creatine-dosage-for-brain",
    badge: "Deep Dive",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "November 19, 2025",
    lastmod: "2025-11-19",
  },
  {
    id: "somatic-reset-guide",
    title: "Best Somatic Reset Techniques in 2026: A Science-Backed Comparison Guide",
    excerpt: "7 techniques compared side by side: somatic breathwork, pendulation, TRE, grounding, cold exposure, and more. What each one does, the science behind it, and how to choose.",
    href: "/product-reviews/somatic-reset-guide",
    canonical: "/product-reviews/somatic-reset-guide",
    badge: "Comparison Guide",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "November 12, 2025",
    lastmod: "2025-11-12",
  },
  {
    id: "breathwork-beginners-guide",
    title: "Breathwork for Beginners: The Complete Science-Backed Guide (2026)",
    excerpt: "5 techniques you can start today, backed by peer-reviewed research on stress, sleep, cognition, and HRV. No equipment, no experience, no courses needed.",
    href: "/product-reviews/breathwork-beginners-guide",
    canonical: "/product-reviews/breathwork-beginners-guide",
    badge: "Beginner's Guide",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "November 5, 2025",
    lastmod: "2025-11-05",
  },
  {
    id: "ceremonial-cacao-benefits-science-review",
    title: "Ceremonial Cacao Benefits: The Ancient Plant Medicine Backed by Modern Science",
    excerpt: "Theobromine, anandamide, magnesium, and over 300 bioactive compounds. What the science says about the most underrated plant medicine in the wellness world, and where to source it.",
    href: "/blog/ceremonial-cacao-benefits-science-review",
    canonical: "/blog/ceremonial-cacao-benefits-science-review",
    badge: "Plant Medicine",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "April 8, 2026",
    lastmod: "2026-04-08",
  },
  {
    id: "biohacking-beginners-guide",
    title: "Biohacking for Beginners: The Complete 2026 Starter Guide",
    excerpt: "No jargon, no overwhelm. A clear, step-by-step framework for taking control of your biology, from free foundations to the right supplements, in the right order.",
    href: "/product-reviews/biohacking-beginners-guide",
    canonical: "/product-reviews/biohacking-beginners-guide",
    badge: "Beginner's Guide",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "October 29, 2025",
    lastmod: "2025-10-29",
  },
  {
    id: "biohacking-supplements-2026",
    title: "Best Biohacking Supplements in 2026: The Optimizer's Evidence-Based Guide",
    excerpt: "The real, research-backed compounds that elite biohackers keep coming back to. Five brands, five layers, one complete stack with the science to back it up.",
    href: "/product-reviews/biohacking-supplements-2026",
    canonical: "/product-reviews/biohacking-supplements-2026",
    badge: "Full Stack Guide",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "October 22, 2025",
    lastmod: "2025-10-22",
  },
  {
    id: "red-light-therapy-science-benefits-devices",
    title: "Red Light Therapy: The Science, the Benefits, and the Devices Worth Buying in 2026",
    excerpt: "Red light therapy is one of the most researched biohacking tools available. Here is what the science actually shows, what it will not do, and the three brands I personally recommend with exclusive discount codes.",
    href: "/blog/red-light-therapy-science-benefits-devices",
    canonical: "/blog/red-light-therapy-science-benefits-devices",
    badge: "Complete Guide",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "October 8, 2025",
    lastmod: "2025-10-08",
  },
  {
    id: "psilocybin-science-research-2025",
    title: "Psilocybin: The Science, the Research, and What's Actually Happening in 2025",
    excerpt: "Johns Hopkins, Imperial College, the FDA's Breakthrough Therapy Designation, and clinical trials across four continents. Here is what the research actually shows about psilocybin, from brain science to microdosing and the legal landscape.",
    href: "/blog/psilocybin-science-research-2025",
    canonical: "/blog/psilocybin-science-research-2025",
    badge: "Plant Medicine",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "October 1, 2025",
    lastmod: "2025-10-01",
  },
  {
    id: "rhonda-patrick-multivitamin",
    title: "Why Your \"Healthy\" Diet Probably Has Gaps. And What To Do About It",
    excerpt: "Dr. Rhonda Patrick takes a multivitamin every single day. Here's the science behind why, from the Triage Theory to the COSMOS trials, and what to look for in a quality supplement.",
    href: "/product-reviews/rhonda-patrick-multivitamin",
    canonical: "/product-reviews/rhonda-patrick-multivitamin",
    badge: "Science-Backed",
    badgeColor: "bg-[#c4622d]/15 text-[#8b3a1a] border-[#c4622d]/25",
    date: "October 15, 2025",
    lastmod: "2025-10-15",
  },
];

export const legacyRedirects: Record<string, string> = {
  "/quantum-healing": "/somatic-reset",
  "/discounts-coupon-codes": "/discount-codes",
  "/product-reviews/creatine-dosage-for-brain": "/blog/creatine-dosage-for-brain",
  "/product-reviews/mouth-breathing-mouth-taping": "/blog/mouth-breathing-mouth-taping",
  "/product-reviews/mct-oil-benefits-c8-vs-c10-powder-vs-oil": "/blog/mct-oil-benefits-c8-vs-c10-powder-vs-oil",
  "/product-reviews/tonic-herbs-guide": "/blog/tonic-herbs-guide",
  "/product-reviews/earthrunners-review": "/blog/earthrunners-review",
  "/product-reviews/energybits-spirulina-chlorella-review": "/blog/energybits-spirulina-chlorella-review",
  "/product-reviews/bacillus-subtilis-bacillus-coagulans-probiotic-guide": "/blog/bacillus-subtilis-bacillus-coagulans-probiotic-guide",
  "/product-reviews/reishi-schisandra-daily-tonic-herbs": "/blog/reishi-schisandra-daily-tonic-herbs",
  "/product-reviews/magnesium-deficiency-supplement-guide": "/blog/magnesium-deficiency-supplement-guide",
  "/product-reviews/pumpkin-seed-oil-supplement-stack-benefits": "/blog/pumpkin-seed-oil-supplement-stack-benefits",
  "/product-reviews/omega-3-complete-guide-epa-dha-fish-oil-vs-algae": "/blog/omega-3-complete-guide-epa-dha-fish-oil-vs-algae",
};

const _extraKnownPaths = [
  "/product-reviews",
  "/blog/rhonda-patrick-multivitamin",
  "/blog/biohacking-supplements-2026",
  "/blog/biohacking-beginners-guide",
  "/blog/somatic-reset-guide",
];

function _buildKnownPublicPaths(): Set<string> {
  const paths = new Set<string>();
  for (const route of staticRoutes) paths.add(route.path);
  for (const route of eventRoutes) paths.add(route.path);
  for (const post of blogPosts) {
    paths.add(post.canonical);
    if (!legacyRedirects[post.href]) {
      paths.add(post.href);
    }
  }
  for (const p of _extraKnownPaths) paths.add(p);
  return paths;
}

export const knownPublicPaths = _buildKnownPublicPaths();
